all:
  vars:
    ansible_user: lawaloladelesulaiman
    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
    ansible_ssh_common_args: >-
      -o ProxyCommand="gcloud compute start-iap-tunnel %h %p
      --listen-on-stdin
      --project=lawal-project-84096
      --zone=europe-west2-a
      --verbosity=warning"
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null

  children:
    dev:
      hosts:
        terraform-devops-vm:

    prod:
      hosts:
        terraform-prod-vm:
